name: Primer CI

on:
  push:
    paths:
      - ".github/workflows/primer_CI.yml"

jobs:
  crear-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Probar version de docker
        run: docker --version 
      
      - name: Montar imagen docker del entrenamiento
        run: docker build -t container_train -f docker/train/Dockerfile
      
      - name: Correr container_train
        run: docker run container_train   